[package]
name = "tauri-plugin-rampage-edge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
links = "tauri-plugin-rampage-edge"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }

[dependencies]
serde.workspace = true
tauri = "2"
thiserror.workspace = true

