[package]
name = "rampage-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
clap.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
iroh.workspace = true
rand.workspace = true
rampage-mesh = { path = "../rampage-mesh" }
rampage-policy = { path = "../rampage-policy" }
rampage-protocol = { path = "../rampage-protocol" }
rampage-storage = { path = "../rampage-storage" }
serde.workspace = true
reqwest.workspace = true
serde_json.workspace = true
sha2.workspace = true
sysinfo.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_System_Power"] }
