[package]
name = "rampage-mesh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
hex.workspace = true
iroh.workspace = true
rampage-protocol = { path = "../rampage-protocol" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true
windows-core.workspace = true

[dev-dependencies]
tokio.workspace = true
